//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluasiKknm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvaluasiKknmDbContext : DbContext
    {
        public EvaluasiKknmDbContext()
            : base("name=EvaluasiKknmDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akun> Akuns { get; set; }
        public virtual DbSet<Desa> Desas { get; set; }
        public virtual DbSet<DosenPembimbing> DosenPembimbings { get; set; }
        public virtual DbSet<Indikator> Indikators { get; set; }
        public virtual DbSet<Kabupaten> Kabupatens { get; set; }
        public virtual DbSet<Kecamatan> Kecamatans { get; set; }
        public virtual DbSet<KelompokKkn> KelompokKkns { get; set; }
        public virtual DbSet<Mahasiswa> Mahasiswas { get; set; }
        public virtual DbSet<Pemda> Pemdas { get; set; }
        public virtual DbSet<Penilaian> Penilaians { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Provinsi> Provinsis { get; set; }
        public virtual DbSet<Universita> Universitas { get; set; }
    }
}
