//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluasiKknm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indikator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indikator()
        {
            this.Penilaians = new HashSet<Penilaian>();
        }
    
        public string KodeDesa { get; set; }
        public int IdIndikator { get; set; }
        public string Username { get; set; }
        public string Judul { get; set; }
        public string Deskripsi { get; set; }
        public Nullable<bool> Konfirmasi { get; set; }
    
        public virtual Akun Akun { get; set; }
        public virtual Desa Desa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penilaian> Penilaians { get; set; }
    }
}
