//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluasiKknm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentar
    {
        public int IdPenilaian { get; set; }
        public int IdKomentar { get; set; }
        public string DescKomentar { get; set; }
    
        public virtual Penilaian Penilaian { get; set; }
    }
}
