//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluasiKknm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penilaian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Penilaian()
        {
            this.Komentars = new HashSet<Komentar>();
        }
    
        public int IdPenilaian { get; set; }
        public string Username { get; set; }
        public string KodeDesa { get; set; }
        public int IdIndikator { get; set; }
        public int IdKel { get; set; }
        public int Id { get; set; }
        public string Alasan { get; set; }
        public Nullable<int> Skor { get; set; }
    
        public virtual Akun Akun { get; set; }
        public virtual Indikator Indikator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komentar> Komentars { get; set; }
        public virtual Program Program { get; set; }
    }
}
