//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluasiKknm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penilaian
    {
        public string KodeDesa { get; set; }
        public int IdIndikator { get; set; }
        public int IdKel { get; set; }
        public int Id { get; set; }
        public int IdPenilaian { get; set; }
        public string Username { get; set; }
        public string Komentar { get; set; }
        public Nullable<int> Skor { get; set; }
    
        public virtual Akun Akun { get; set; }
        public virtual Indikator Indikator { get; set; }
        public virtual Program Program { get; set; }
    }
}
