//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluasiKknm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.Penilaians = new HashSet<Penilaian>();
        }
    
        public int IdKel { get; set; }
        public int Id { get; set; }
        public string NamaProgram { get; set; }
        public string Deskripsi { get; set; }
        public Nullable<bool> Realisasi { get; set; }
    
        public virtual KelompokKkn KelompokKkn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penilaian> Penilaians { get; set; }
    }
}
